version: '3.4'

# Start the Api (Generator) and the Mail client images

services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/generatorapi:multibuild
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"